version: '3'

services:
  db:
    build:
      context: ./db
      args:
        MYSQL_DATABASE: mydb
        MYSQL_ROOT_PASSWORD: root
    restart: always
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_ROOT_PASSWORD: root

  wordpress:
    build:
      context: ./php
    depends_on:
      - db
    ports:
      - "8000:80"
    volumes:
      - ./html:/var/www/html
    